Finished GenServer Cache
acmfi/acm_bot pull request #10
Opened 2019-03-15 08:56 UTC by Alfedi

Thanks to @Ironjanowar, I were able to finish this enhacement related to #6.
I use a GenServer to store the `file_id` variable so it's no necessary to upload the document to Telegram all the time.

2019-03-15 13:37 UTC, rockneurotiko requested changes
Comments about the Cache, I think that having a more generic cache is better than having only one that handles one string

2019-03-15 13:37 UTC, rockneurotiko commented on lib/acm_bot.ex
> +      AcmBot.Cache
I recommend to start the Cache before the Bot, in that case you won't have any problems like receiving an update with a file and trying to go to the Cache and that it doesn't exists

2019-03-15 13:37 UTC, rockneurotiko commented on lib/acm_bot/cache.ex
> +    {:ok, ""}
A cache that only saves an ID it's a little weird. What would happen if you need to save another file ID here? Would you create 2 AcmBot.Cache, one for every ID?

The typical way of doing this is having the inner state as a map, and accessing the cache with a key, for example:
`AcmBot.Cache.get(:file_id_comida)` and `AcmBot.Cache.put(:file_id_comida, file_id)`

2019-03-17 13:18 UTC, Ironjanowar requested changes
I think that the child starting order is important, didn't thing about that. Thanks @rockneurotiko

2019-04-01 16:58 UTC, rockneurotiko approved these changes
Mis 🔟 (Just change the children order before merging)

2019-04-01 18:57 UTC, Ironjanowar approved these changes

2019-04-01 18:58 UTC, merged